/* Populate database with sample data. */

INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Gabumon', '2018-11-15',  2, true, 8);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Agumon', '2020-02-03',  0, true, 10.23);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Pikachu', '2021-01-07',  1, false, 15.04);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Devimon', '2017-05-12',  5, true, 11);

INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Charmander', '2020-02-08',  0, false, -11);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Plantmon', '2021-11-15',  2, true, -5.7);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Squirtle', '1993-04-02',  3, false, -12.13);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Angemon', '2005-06-12',  1, true, -45);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ('Boarmon', '2005-06-7',  7, true, 20.4);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ( 'Blossom', '1998-10-13',  3, true, 17);
INSERT INTO ANIMALS (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG) VALUES ( 'Ditto', '2022-05-14',  4, true, 22);


INSERT INTO owners (full_name, age) VALUES
   ('Sam Smith', 34),
   ('Jennifer Orwell', 19),
   ('Bob', 45),
   ('Melody Pond', 77),
   ('Dean Winchester', 14),
   ('Jodie Whittaker', 38);


INSERT INTO species (name) VALUES
   ('Pokemon'),
   ('Digimon');

UPDATE animals
SET species_id=2
WHERE name LIKE '%mon';

UPDATE animals
SET species_id=1
WHERE species_id IS NULL;