/* Database schema to keep the structure of entire database. */

CREATE TABLE animals ( 
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(20) NOT NULL, 
    DATE_OF_BIRTH DATE, 
    ESCAPE_ATTEMPTS INT, 
    NEUTERED BOOLEAN, 
    WEIGHT_KG REAL
);

ALTER TABLE animals add column SPECIES VARCHAR(60);

CREATE TABLE owners(ID INT GENERATED ALWAYS AS IDENTITY, FULL_NAME VARCHAR(60), AGE INT, PRIMARY KEY(ID));

CREATE TABLE species(ID INT GENERATED ALWAYS AS IDENTITY, NAME VARCHAR(60), PRIMARY KEY(ID));

ALTER TABLE ANIMALS DROP COLUMN SPECIES;

ALTER TABLE ANIMALS ADD COLUMN SPECIES_ID INT REFERENCES SPECIES (ID);

ALTER TABLE ANIMALS ADD COLUMN OWNER_ID INT REFERENCES OWNERS (ID);

CREATE TABLE VETS(ID INT GENERATED ALWAYS AS IDENTITY, NAME VARCHAR(60), AGE INT, DATE_OF_GRADUATION DATE, PRIMARY KEY(ID));

CREATE TABLE specializations(VETS_ID INT REFERENCES VETS (ID), SPECIES_ID INT REFERENCES SPECIES (ID));

CREATE TABLE visits(VETS_ID INT REFERENCES VETS(ID), ANIMAL_ID INT REFERENCES ANIMALS(ID), VISIT_DATE DATE );